"""Tool registry + the select() seam.

In-memory, assembled from providers (providers = source of truth). select(context)
-> subset is the seam: v1 is a tag filter; semantic retrieval swaps in later behind
the SAME signature. Dispatch is wrapped here so every tool call is timed + counted,
and raw errors become model-readable teaching messages (ModelRetry).
"""
from __future__ import annotations
import functools
import time
from dataclasses import dataclass
from typing import Any, Callable

from pydantic_ai.exceptions import ModelRetry
from pydantic_ai.tools import Tool as PydTool

from . import metrics


@dataclass
class Tool:
    """The uniform contract every provider emits. The model-facing JSON schema is
    generated by Pydantic AI from `func`'s signature + docstring — we don't
    hand-maintain it (minimum owned code). `tags`/`example` are selection-side."""
    name: str
    description: str
    tags: list[str]
    func: Callable[..., Any]      # plain callable with type hints + docstring
    provider: str = "native"
    example: dict | None = None
    schema: dict | None = None    # explicit JSON schema for external lanes (n8n/openapi)

    def as_pydantic_tool(self) -> PydTool:
        wrapped = self._wrapped()
        if self.schema is not None:   # external lane: model-facing schema from manifest/spec
            return PydTool.from_schema(
                wrapped, name=self.name, description=self.description,
                json_schema=self.schema,
            )
        return PydTool(wrapped, name=self.name, description=self.description, max_retries=2)

    def _wrapped(self) -> Callable:
        """Instrument dispatch: latency, counts, and teaching-error mapping."""
        fn, provider, name = self.func, self.provider, self.name

        @functools.wraps(fn)  # copy real signature (__wrapped__) so Pydantic AI binds args by name
        def runner(*args, **kwargs):
            start = time.perf_counter()
            try:
                result = fn(*args, **kwargs)
                metrics.TOOL_CALLS.labels(provider, name, "ok").inc()
                return result
            except ModelRetry:
                metrics.TOOL_RETRY.labels(name).inc()
                metrics.TOOL_CALLS.labels(provider, name, "retry").inc()
                raise
            except Exception as e:  # raw error -> model-readable teaching message
                metrics.TOOL_ERRORS.labels(provider, name, type(e).__name__).inc()
                metrics.TOOL_CALLS.labels(provider, name, "error").inc()
                raise ModelRetry(f"{name} failed: {e}") from e
            finally:
                metrics.TOOL_LATENCY.labels(provider, name).observe(
                    time.perf_counter() - start
                )

        return runner


class Registry:
    def __init__(self) -> None:
        self._tools: dict[str, Tool] = {}

    def add(self, tool: Tool) -> None:
        self._tools[tool.name] = tool

    def add_provider(self, tools: list[Tool]) -> None:
        for t in tools:
            self.add(t)

    def all(self) -> list[Tool]:
        return list(self._tools.values())

    def select(self, context: str, *, tags: set[str] | None = None) -> list[Tool]:
        """The seam. v1: filter by tag overlap; if no tags requested or none match,
        fall back to all (registry is small). Swap for semantic retrieval later
        WITHOUT changing callers."""
        if tags:
            hit = [t for t in self.all() if tags.intersection(t.tags)]
            if hit:
                return hit
        return self.all()
